### ISSUE TITLE
Visualize intermediate feature map?

### ISSUE THREAD

**Issue by Zzlongjuanfeng** [zhoubolei/CAM#27]
What if i want to visualize the intermediate feature map and its channel is difference from the last layer. For example, Visualize the layer3 in resnet18 in pytorch.

**Comment by kartik1395** [comment]
Yes I want to do the same for my network as well. To able able to visualize a layer that has 256 channels.

**Comment by zhoubolei** [comment]
https://github.com/zhoubolei/cnnvisualizer 
you can take a look at the python script here

**Comment by kartik1395** [comment]
Can this CAM not be used for layers with more than one channels ?
